<?php

use Commie\CSVColMapper;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-15 at 16:48:20.
 */
class CSVColMapperTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CSVColMapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CSVColMapper(array());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Commie\CSVColMapper::mapLabel
     * @todo   Implement testMapLabel().
     */
    public function testMapLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
